# Generated by Django 3.2.5 on 2021-07-22 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("entry_number", models.IntegerField(default=0)),
                ("research_title", models.CharField(max_length=255)),
                ("authors", models.TextField()),
                ("year", models.IntegerField()),
                ("date", models.DateField()),
                ("preprint", models.BooleanField()),
                ("link", models.URLField()),
                ("abstract", models.TextField()),
                ("doi", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
