# Generated by Django 3.2.5 on 2021-07-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchpage",
            name="research_title",
        ),
    ]
