# Generated by Django 3.2.5 on 2021-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0005_remove_researchindexpage_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchindexpage",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
